# Generated by Django 2.1.7 on 2019-03-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_umpire', '0003_auto_20190313_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('1', 'Cuenca'), ('2', 'Quito'), ('3', 'Guayaquil')], default='1', max_length=1),
        ),
    ]
