# Generated by Django 2.1.7 on 2019-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_umpire', '0008_auto_20190312_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
