# Generated by Django 2.1.7 on 2019-03-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0004_auto_20190306_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticion_text', models.CharField(max_length=200)),
            ],
        ),
    ]
