# Generated by Django 2.1.7 on 2019-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0005_repeticion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='carrera_text',
        ),
    ]
