# Generated by Django 2.1.7 on 2019-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0006_remove_carrera_carrera_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_text', models.CharField(max_length=200)),
            ],
        ),
    ]
